import { Horse } from "./scoreboard";

const initialHorses: Horse[] = [
    {
      id: 1,
      number: 5,
      name: "Thunderbolt",
      jockey: "John Smith",
      time: "2:03.45",
      rank: 1,
      odds: "3:1",
    },
    {
      id: 2,
      number: 3,
      name: "Silver Arrow",
      jockey: "Emma Johnson",
      time: "2:03.67",
      rank: 2,
      odds: "4:1",
    },
    {
      id: 3,
      number: 7,
      name: "Midnight Star",
      jockey: "Michael Brown",
      time: "2:03.89",
      rank: 3,
      odds: "5:1",
    },
    {
      id: 4,
      number: 1,
      name: "Golden Hoof",
      jockey: "Sarah Davis",
      time: "2:04.12",
      rank: 4,
      odds: "6:1",
    },
    {
      id: 5,
      number: 9,
      name: "Whirlwind",
      jockey: "David Wilson",
      time: "2:04.34",
      rank: 5,
      odds: "8:1",
    },
    {
      id: 6,
      number: 2,
      name: "Lucky Charm",
      jockey: "Lisa Anderson",
      time: "2:04.56",
      rank: 6,
      odds: "10:1",
    },
    {
      id: 7,
      number: 8,
      name: "Desert Storm",
      jockey: "Robert Taylor",
      time: "2:04.78",
      rank: 7,
      odds: "12:1",
    },
    {
      id: 8,
      number: 4,
      name: "Blazing Comet",
      jockey: "Jessica Lee",
      time: "2:05.01",
      rank: 8,
      odds: "15:1",
    },
    {
      id: 9,
      number: 6,
      name: "Shadow Dancer",
      jockey: "Thomas White",
      time: "2:05.23",
      rank: 9,
      odds: "18:1",
    },
    {
      id: 10,
      number: 10,
      name: "Mystic Wind",
      jockey: "Oliver Green",
      time: "2:05.45",
      rank: 10,
      odds: "20:1",
    },
    {
      id: 11,
      number: 12,
      name: "Crimson Tide",
      jockey: "Sophia Martinez",
      time: "2:05.67",
      rank: 11,
      odds: "25:1",
    },
    {
      id: 12,
      number: 11,
      name: "Frost Fury",
      jockey: "Daniel Cooper",
      time: "2:05.89",
      rank: 12,
      odds: "30:1",
    },
    {
      id: 13,
      number: 14,
      name: "Thunder Cloud",
      jockey: "Emily Foster",
      time: "2:06.12",
      rank: 13,
      odds: "35:1",
    },
    {
      id: 14,
      number: 13,
      name: "Wildfire",
      jockey: "James Parker",
      time: "2:06.34",
      rank: 14,
      odds: "40:1",
    },
    {
      id: 15,
      number: 15,
      name: "Royal Flush",
      jockey: "Olivia Scott",
      time: "2:06.56",
      rank: 15,
      odds: "45:1",
    },
    {
      id: 16,
      number: 16,
      name: "Emerald Dream",
      jockey: "William Turner",
      time: "2:06.78",
      rank: 16,
      odds: "50:1",
    },
    {
      id: 17,
      number: 17,
      name: "Sapphire Surge",
      jockey: "Ava Richards",
      time: "2:07.01",
      rank: 17,
      odds: "55:1",
    },
  ];
  
  export default initialHorses;